spring:
  application:
    name: spring-boot-das-trincheiras
  threads:
    virtual:
      enabled: true
server:
  servlet:
      context-path: /${spring.application.name}
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20